#!/usr/bin/env ruby

git_bundles = [ 
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/vim-scripts/python.vim--Vasiliev.git",
  "git://github.com/vim-scripts/django.vim.git",
  "git://github.com/motemen/git-vim.git",
  "git://github.com/kevinw/pyflakes-vim",
  "git://github.com/kevinw/pyflakes.git",
  "git://github.com/altercation/vim-colors-solarized.git",
  "https://github.com/vim-scripts/Command-T",
  "https://github.com/int3/vim-extradite",
]

vim_org_scripts = [
#  ["IndexedSearch", "7062",  "plugin"],
#  ["jquery",        "2416", "syntax"],
#  ["pyflakes",	    "2441",  "plugin"],
   ["blackboard",    "11225", "colors"],
   ["calmbreeze",    "16283", "colors"],
   ["atom",          "15570", "colors"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end

# Compile the Command-T C extension.
FileUtils.cd("./Command-T/ruby/command-t")
`ruby extconf.rb; make`
