#!/bin/bash
# This hook is run after every virtualenv is activated.

export TARGET_DIR=`basename $VIRTUAL_ENV`

if [ -d $DEV_DIR/$TARGET_DIR ]
then
    cd $DEV_DIR/$TARGET_DIR
elif [ -n "$no_cd" ]
then
    # Make sure we clear the no_cd var.
    unset no_cd
fi