#!/bin/bash
# This hook is run after every virtualenv is deactivated.

# Re-set gem paths  $PATH is automatically reset for us.
export GEM_HOME=$OLD_GEM_HOME
unset OLD_GEM_HOME
export GEM_PATH=$OLD_GEM_PATH
unset OLD_GEM_PATH
