#!/bin/bash
# This hook is run after a new virtualenv is activated.
pip install Sphinx

# Install Bundler so we can manage RubyGems for our virtualenv.
# See http://bruno.im/2011/sep/29/streamline-your-django-workflow/
gem install bundler

# Install the default RubyGems for python environments
bundle install --gemfile=~/Configs/Gemfile
